apiVersion: v1
kind: Pod
metadata:
  name: vardhan
spec:
  containers:
    - name: container1
      image: nginx
      ports:
       - containerPort: 80 
   

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-matchlabels
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
   metadata:
     labels:
       env: dev
       tier: development
   spec:
    containers:
      image: nginx
      ports:
        containerport: 80
    


