#liveness-Exec
#liveness-health   kubelet -> when to restart the container if it is unhealthy state.
#Readiness-Traffic Kubelet -> when to accept the traffic into container after it is in health state.
apiVersion: v1 
kind: Pod
metadata:
  name: liveness-exec
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh','-c','echo app is running && sleep 3600']
      livenessProbe:
        exec:
          command: ["echo", "hello app!"]
        initialDelaySeconds: 5
        periodSeconds: 5


---
#liveness-http
apiVersion: v1 
kind: Pod
metadata:
  name: liveness-http
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80 #(container Port)
        initialDelaySeconds: 5
        periodSeconds: 5
