#storageclasses
apiVersion: storage.k8s.io/v1  
kind: StorageClass
metadata:
  name: faster #user-friendly
allowVolumeExpansion: true #if you want to increase the disk size for future uses set as true 
#this changes when vendor changes (vendors like gcp,aws,azure)
provisioner: kubernetes.io/gce-pd  #you can visit the gke storageclass in google
parameters:
  type: pd-ssd  


---
#in dynamic provisioning you don't need to create pv when you create pvc it automatically creates pv(disk in GCP)in GKE BOUND happens 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: faster #it should match storageclass in our cluster

---
#in dynamic provisioning volumemod
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

#default-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-app
  template:
    metadata:
      labels:
        app: new-app
    spec:
     volumes:
       - name: my-volume
         persistentVolumeClaim:
           claimName: pvc-claim-default
     containers:
       - name: nginx-webserver
         image: nginx
         ports:
          - containerPort: 80
         volumeMounts:
          - name: my-volume
            mountPath: "/vardhan"


#created-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-app
  template:
    metadata:
      labels:
        app: new-app
    spec:
     volumes:
       - name: my-volume-other
         persistentVolumeClaim:
           claimName: pvc-dynamic
     containers:
       - name: nginx-webserver
         image: nginx
         ports:
          - containerPort: 80
         volumeMounts:
          - name: my-volume-other
            mountPath: "/vardhan"
