#Qualityofscale of pods
#Best-effort -> low priority & Most likely PODS to be killed first by K8S when out of Storage
#burstable -> when you write requests and limits in Pods(container resources) then K8S marks them as burstable
#Quareented -> when you write requests and limits as same in Pods(container resources) then K8S marks them as Quareented 
#but requests and limits must match
apiVersion: v1
kind: Pod
metadata:
  name: best-effort
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    



